CREATE OR REPLACE TYPE ugpoint_g3 AS 
object(nid INTEGER, rid INTEGER, side INTEGER, offset NUMBER, t1 NUMBER, t2 NUMBER, pos1 NUMBER, pos2 NUMBER);
/ 

CREATE OR REPLACE TYPE UGPOINT_V_G3 AS VARRAY(10000) OF ugpoint_g3;
/ 
CREATE OR REPLACE TYPE MGPOINT_V_G3 AS
object(units UGPOINT_V_G3);
/
CREATE OR REPLACE TYPE upoint_g3 AS
object(point1_x NUMBER, point1_y NUMBER, point2_x NUMBER, point2_y NUMBER, t1 NUMBER, t2 NUMBER); 
/

 CREATE OR REPLACE TYPE UPOINT_V_G3 AS VARRAY(10000) OF upoint_g3;
/ 
 
 CREATE OR REPLACE TYPE MPOINT_V_G3 AS
 object(units UPOINT_V_G3);
 / 


 -- java oracle.jpub.Doit -user=sysman/oracle -sql= UGPOINT_V_G3:UGPOINT_V_G3,UGPOINT_G3:UGPOINT_G3,MGPOINT_V_G3:MGPOINT_V_G3,UPOINT_G3:UPOINT_G3,UPOINT_V_G3:UPOINT_V_G3,MPOINT_V_G3:MPOINT_V_G3